Repository emidioreb/mercado-fresco-lerigophers, pull requests merged in 2022-06, with the labels that each got.

#1 feat: sellers crud Implementation
  cmd/server/controllers/sellers.go
  cmd/server/main.go
  internal/sellers/model.go
  internal/sellers/repository.go
  internal/sellers/service.go
  pkg/web/response.go
Labels: enhancement

#2 Feature warehouses 2
  cmd/server/controllers/warehouses.go
  cmd/server/main.go
  internal/warehouses/model.go
  internal/warehouses/repository.go
  internal/warehouses/service.go
Labels: enhancement

#4 fix: adjust wrong line codes
  cmd/server/controllers/warehouses.go
  cmd/server/main.go
Labels: bug

#5 feat: create patch request(alter currentCapacity)
  cmd/server/controllers/sections.go
  cmd/server/main.go
  internal/sections/repository.go
  internal/sections/service.go
Labels: enhancement

#9 fix: adjusting router config of feature2 on main.go file
  cmd/server/main.go
Labels: bug

#12 Feature upd dynamic
  cmd/server/controllers/sections.go
  cmd/server/main.go
  internal/sections/repository.go
  internal/sections/service.go
Labels: enhancement

#14 replace put to patch on employees
  cmd/server/controllers/employees.go
  cmd/server/main.go
  internal/employees/repository.go
  internal/employees/service.go
  internal/sections/repository.go
Labels: enhancement

#13 Feature buyer 6.1
  cmd/server/controllers/buyer.go
  cmd/server/main.go
  internal/buyer/repository.go
  internal/buyer/service.go
Labels: enhancement

#18 refactor a Update method on employee service.go
  internal/employees/service.go
Labels: enhancement

#17 adjust PATCH method to receive dynamic params when sending a body
  cmd/server/controllers/sellers.go
  cmd/server/main.go
  internal/sellers/repository.go
  internal/sellers/service.go
Labels: enhancement

#22 Adjust validation of SectionNumber
  internal/sections/service.go
Labels: enhancement

#23 Adjust converting fields
  internal/sections/repository.go
Labels: enhancement

#25 remove redundant returns and forbidden empty warehouse code
  cmd/server/controllers/warehouses.go
Labels: enhancement

#28 adjusting error messages and empty values of warehouse_code
  cmd/server/controllers/warehouses.go
  internal/warehouses/repository.go
  internal/warehouses/service.go
Labels: enhancement

#31 Adjust to validate unique id - section_number
  cmd/server/controllers/sections.go
  internal/sections/repository.go
Labels: enhancement

#36 Feature sellers 1 tests
  cmd/server/controllers/sellers.go
  cmd/server/controllers/sellers_test.go
  go.mod
  go.sum
  internal/sellers/mocks/Repository.go
  internal/sellers/mocks/Service.go
  internal/sellers/service.go
  internal/sellers/service_test.go
Labels: tests

#37 Feature products 4 tests
  cmd/server/controllers/products.go
  cmd/server/controllers/products_test.go
  go.mod
  go.sum
  internal/products/mocks/Repository.go
  internal/products/mocks/Service.go
  internal/products/service.go
  internal/products/service_test.go
Labels: tests
